export enum UrlsNamesEnums {
  DealerAuthentication = 'auth-broker',
  ClientAuthentication = 'auth-client',
  MainPage = 'main-form',
  LoanCalculation = 'loan-calculation',
  Processing = 'processing',
  DocumentsAndPayments = 'documents-payments',
  CarOptions = 'car-options',
  CarOwner = 'car-owner',
  Drivers = 'drivers',
  CreditOptions = 'credit-options',
  InsurancePoliciesOptions = 'insurance-options',
  ProductsCalculation = 'products-calculation',
  PersonalData = 'personal-data',
  ClientJobData = 'client-job',
  Summary = 'summary',
  Approval = 'approval',
}
