export enum CalculationLoanPageEnum {
  SET_SELECTED_CLIENT = '[CALCULATION_LOAN_PAGE] Set selected client',
  GET_CASCO_POLICIES = '[CALCULATION_LOAN_PAGE] Get casco policies',
  GET_CASCO_POLICIES_SUCCESS = '[CALCULATION_LOAN_PAGE] Loaded Success',
  GET_CASCO_POLICIES_FAILURE = '[CALCULATION_LOAN_PAGE] Loaded Failure',
}
