export enum CalculationLoanPageEnum {
  CREATE_CAR = '[CALCULATION_LOAN_PAGE] Create car',
  CREATE_CAR_SUCCESS = '[CALCULATION_LOAN_PAGE] Car created successfully',
  CREATE_CAR_FAILURE = '[CALCULATION_LOAN_PAGE] Car created unsuccessfully',
  SET_CAR_ID = '[CALCULATION_LOAN_PAGE] Set car id',
  EDIT_CAR_OPTIONS = '[CALCULATION_LOAN_PAGE] Edit car options',
  EDIT_CAR_OPTIONS_SUCCESS = '[CALCULATION_LOAN_PAGE] Car edited successfully',
  EDIT_CAR_OPTIONS_FAILURE = '[CALCULATION_LOAN_PAGE] Car edited unsuccessfully',
  CONNECT_CAR_TO_CLIENT_SUCCESS = '[CALCULATION_LOAN_PAGE] Car connected to client successfully',
  CONNECT_CAR_TO_CLIENT_FAILURE = '[CALCULATION_LOAN_PAGE] Car connected to client unsuccessfully',
  CONNECT_CAR_TO_CLIENT = '[CALCULATION_LOAN_PAGE] Connect car to client',
  GET_SELECTED_CLIENT = '[CALCULATION_LOAN_PAGE] Get selected client',
  SET_SELECTED_CLIENT = '[CALCULATION_LOAN_PAGE] Set selected client',
  GET_CASCO_POLICIES = '[CALCULATION_LOAN_PAGE] Get casco policies',
  GET_CASCO_POLICIES_SUCCESS = '[CALCULATION_LOAN_PAGE] Loaded Success',
  GET_CASCO_POLICIES_FAILURE = '[CALCULATION_LOAN_PAGE] Loaded Failure',
}
